<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('NFL Graphs'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-custom.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/index/home-page.js'))
            ->prependFile($this->basePath('js/players/players.js'))
            ->prependFile($this->basePath('lib/highcharts-ng/src/highcharts-ng.js'))
            ->prependFile($this->basePath('lib/highcharts/js/solid-gauge.js'))
            ->prependFile($this->basePath('lib/highcharts/js/highcharts-more.js'))
            ->prependFile($this->basePath('lib/highcharts/js/highcharts.src.js'))
            ->prependFile($this->basePath('lib/ui-bootstrap/ui-bootstrap-tpls-0.13.1.min.js'))
            ->prependFile($this->basePath('lib/angularjs/angular.min.js'))
            ->prependFile($this->basePath('lib/bootstrap/bootstrap.min.js'))
            ->prependFile($this->basePath('lib/jquery/jquery.min.js'))
            ->prependFile($this->basePath('lib/respond/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('lib/html5shiv/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

<!--        <script src="http://code.highcharts.com/modules/solid-gauge.js"></script>
-->

    </head>
<!--    <body style="background: -moz-linear-gradient(top, rgba(248,248,248,1) 0%, rgba(234,234,234,1) 50%, rgba(248,248,248,1) 100%); /* FF3.6+ */
background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(248,248,248,1)), color-stop(50%,rgba(234,234,234,1)), color-stop(100%,rgba(248,248,248,1))); /* Chrome,Safari4+ */
background: -webkit-linear-gradient(top, rgba(248,248,248,1) 0%,rgba(234,234,234,1) 50%,rgba(248,248,248,1) 100%); /* Chrome10+,Safari5.1+ */
background: -o-linear-gradient(top, rgba(248,248,248,1) 0%,rgba(234,234,234,1) 50%,rgba(248,248,248,1) 100%); /* Opera 11.10+ */
background: -ms-linear-gradient(top, rgba(248,248,248,1) 0%,rgba(234,234,234,1) 50%,rgba(248,248,248,1) 100%); /* IE10+ */
background: linear-gradient(to bottom, rgba(248,248,248,1) 0%,rgba(234,234,234,1) 50%,rgba(248,248,248,1) 100%); /* W3C */">-->
   <body style="background-image:url('img/gray-leather.jpg');background-repeat: 'repeat-y';padding-top:20px">
   <!--<body style="background-image:url('img/rough-cloth.jpg');background-repeat: 'repeat-y';">-->
<!--        <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php /*echo $this->url('home') */?>"><?php /*echo $this->translate('Dashboard') */?></a></li>
                    </ul>
                </div>
            </div>
        </nav>-->
        <div class="container-fluid">
            <?php echo $this->content; ?>
<!--            <hr>
            <footer>
                <p>Created by Eric Miller (2015). </p>
            </footer>-->
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
