<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('NFL Dashboard')?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this
            ->headLink(
                array(
                    'rel' => 'shortcut icon',
                    'type' => 'image/vnd.microsoft.icon',
                    'href' => $this->basePath() . '/img/favicon.ico',
                )
            )
            ->prependStylesheet($this->basePath('lib/select2/3.5.4/select2.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('lib/font-awesome/css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('lib/ui-select/dist/select.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-custom.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/index/home-page.js'))
            ->prependFile($this->basePath('js/players/players.js'))
            ->prependFile($this->basePath('lib/highcharts-ng/src/highcharts-ng.js'))
            ->prependFile($this->basePath('lib/highcharts/js/solid-gauge.js'))
            ->prependFile($this->basePath('lib/highcharts/js/highcharts-more.js'))
            ->prependFile($this->basePath('lib/highcharts/js/highcharts.src.js'))
            ->prependFile($this->basePath('lib/ui-bootstrap/ui-bootstrap-tpls-0.13.1.min.js'))
            ->prependFile($this->basePath('lib/ui-select/dist/select.js'))
            ->prependFile($this->basePath('lib/angularjs/1.3.15/angular-sanitize.min.js'))
            ->prependFile($this->basePath('lib/angularjs/1.3.15/angular.min.js'))
            ->prependFile($this->basePath('lib/bootstrap/bootstrap.min.js'))
            ->prependFile($this->basePath('lib/jquery/jquery.min.js'))
            ->prependFile($this->basePath('lib/respond/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('lib/html5shiv/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

<!--        <script src="http://code.highcharts.com/modules/solid-gauge.js"></script>
-->

    </head>
   <body style="background-image:url('img/gray-leather.jpg');background-repeat: 'repeat-y';padding-top:20px">
       <script>
           (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
               (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
               m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
           })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

           ga('create', 'UA-67529000-1', 'auto');
           ga('send', 'pageview');

       </script>
<!--        <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php /*echo $this->url('home') */?>"><?php /*echo $this->translate('Dashboard') */?></a></li>
                    </ul>
                </div>
            </div>
        </nav>-->
        <div class="container-fluid">
            <?php echo $this->content; ?>
            <footer style="padding-left:10px">
                <hr/>
                <p>Created by Eric Miller (2015). </p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
