<div ng-app="home-page" ng-controller="HomePageCtrl"
    <?php echo $this->ngInit(array('playerData', 'gameData')); ?>>
    <div style="width:100%;height:50px">
        <div style="float:left; display: inline-block; width:60%; padding-left:15px">
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active">
                    <a href="#offense" aria-controls="offense" role="tab" data-toggle="tab" ng-click="currentTab = 'offense'">
                        Team Offense
                    </a>
                </li>
                <li role="presentation">
                    <a href="#drives" aria-controls="drives" role="tab" data-toggle="tab" ng-click="currentTab = 'drives'">
                        Team Drives
                    </a>
                </li>
            </ul>
        </div>
        <div style="float:left; display: inline-block; width:19%; text-align:center; font-size:1.25em; text-decoration: underline">
            Scoreboard
        </div>
        <div style="float:left; display: inline-block; width:20%; text-align:center; font-size:1.25em; text-decoration: underline;">
            Current Drive
        </div>
    </div>
    <div style="width:100%">

        <div class="tab-content" style="float:left; display: inline-block; width:60%;">
            <div role="tabpanel" class="tab-pane active" id="offense">
                <highchart ng-repeat="(key, team) in teams"
                    style="float:left;display: inline-block; width:50%; height:260px"
                           id="chart{{key}}"
                           config="chartConfigs[key]">
                </highchart>
            </div>
            <div role="tabpanel" class="tab-pane" id="drives">
                <div style="width:60%">
                    <highchart ng-repeat="(key, fieldPossessionConfig) in fieldPossessionConfigs"
                        id="fieldPossessionConfig{{key}}"
                        config="fieldPossessionConfigs[key]">
                    </highchart>
                </div>
            </div>
        </div>
        <div style="float:left; display: inline-block; width:39%">
            <div ng-repeat="(key, team) in teams" ng-if="!(key % 2 == 1)">
                <div style="float:left;display: inline-block; width:50%;">
                    <table class="scoreboard">
                        <tbody>
                        <tr style="font-size:2.5em; font-weight: bold">
                            <td>{{gameData[(key) / 2].home_score}} - {{gameData[(key) / 2].away_score}}</td>
                        </tr>
                        <tr style="font-size:1.5em">
                            <td>{{getQuarterTime(gameData[(key) / 2].time)}}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div style="float:left;display: inline-block; width:50%; margin-top:20px; min-height:220px">
                    <highchart
                        id="gauge{{key}}"
                        config="gaugeConfigs[(key) / 2]">
                    </highchart>
                </div>
            </div>
        </div>
    </div>
    <div style="clear: both;"></div>

</div>