<div ng-app="home-page" ng-controller="HomePageCtrl"
    <?php echo $this->ngInit(array('playerData', 'gameData')); ?>>
    <div style="width:100%;height:50px">
        <div style="float:left; display: inline-block; width:60%; padding-left:15px">
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active">
                    <a href="#offense" aria-controls="offense" role="tab" data-toggle="tab" ng-click="currentTab = 'offense'">
                        Team Offense
                    </a>
                </li>
                <li role="presentation">
                    <a href="#drives" aria-controls="drives" role="tab" data-toggle="tab" ng-click="currentTab = 'drives'">
                        Team Drives
                    </a>
                </li>
            </ul>
        </div>
        <div ng-show="currentTab == 'offense'">
            <div style="float:left; display: inline-block; width:19%; text-align:center; font-size:1.25em; text-decoration: underline">
                <span>Scoreboard</span>
            </div>
            <div style="float:left; display: inline-block; width:20%; text-align:center; font-size:1.25em; text-decoration: underline;">
                <span>Current Drive</span>
            </div>
        </div>
        <div ng-show="currentTab == 'drives'" style="float:right;display:inline-block;margin-right:30px">
            <button class="btn filterButton" ng-click="driveFilter = 'all'" ng-class="{active: driveFilter == 'all'}">
                All
            </button>
            <button class="btn filterButton" ng-click="driveFilter = 'Q1'" ng-class="{active: driveFilter == 'Q1'}">
                1st Quarter
            </button>
            <button class="btn filterButton" ng-click="driveFilter = 'Q2'" ng-class="{active: driveFilter == 'Q2'}">
                2nd Quarter
            </button>
            <button class="btn filterButton" ng-click="driveFilter = 'Q3'" ng-class="{active: driveFilter == 'Q3'}">
                3rd Quarter
            </button>
            <button class="btn filterButton" ng-click="driveFilter = 'Q4'" ng-class="{active: driveFilter == 'Q4'}">
                4th Quarter
            </button>
        </div>
    </div>
    <div style="width:100%">

        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="offense">
                <div ng-repeat="(key, team) in teams">
                    <highchart
                        style="float:left;display: inline-block; width:30%; height:260px"
                        id="chart{{key}}"
                        config="chartConfigs[key]">
                    </highchart>
                    <div ng-if="(key % 2)" style="float:left;display: inline-block; width:39%">
                        <div style="width:50%; float:left;display: inline-block;">
                            <table class="scoreboard">
                                <tbody>
                                <tr>
                                    <td>{{gameData[(key - 1) / 2].home_team}}</td>
                                    <td></td>
                                    <td>{{gameData[(key - 1) / 2].away_team}}</td>
                                </tr>
                                <tr style="font-size:2.5em; font-weight: bold">
                                    <td>{{gameData[(key - 1) / 2].home_score}}</td>
                                    <td>-</td>
                                    <td>{{gameData[(key - 1) / 2].away_score}}</td>
                                </tr>
                                <tr style="font-size:1.5em">
                                    <td colspan="3">{{getQuarterTime(gameData[(key - 1) / 2].time)}}</td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                        <div style="width:50%; float:left; display:inline-block; margin-top:20px; min-height:220px">
                            <highchart
                                id="gauge{{key}}"
                                config="gaugeConfigs[(key - 1) / 2]">
                            </highchart>
                        </div>
                    </div>
                </div>
            </div>
            <div role="tabpanel" class="tab-pane" id="drives">
                <div>

                    <highchart ng-repeat="(key, fieldPossessionConfig) in fieldPossessionConfigs"
                               ng-if="currentTab == 'drives' && !loadingPlayData"
                        style="float:left;display: inline-block;width:100%;height:260px;padding:10px 25px 0 25px"
                        id="fieldPossessionConfig{{key}}"
                        config="fieldPossessionConfigs[key]">
                    </highchart>
                    <div ng-if="currentTab == 'drives' && loadingPlayData"
                         style="float:left;display: inline-block;width:100%;height:260px;padding:10px 25px 0 25px;text-align:center">
                        <i class="fa fa-spinner fa-spin fa-3x"></i>
                    </div>
                </div>
            </div>
        </div>
<!--        <div style="float:left; display: inline-block; width:39%">
            <div ng-repeat="(key, team) in teams" ng-if="!(key % 2 == 1)">
                <div style="float:left;display: inline-block; width:50%;">
                    <table class="scoreboard">
                        <tbody>
                        <tr>
                            <td>{{gameData[(key) / 2].home_team}}</td>
                            <td></td>
                            <td>{{gameData[(key) / 2].away_team}}</td>
                        </tr>
                        <tr style="font-size:2.5em; font-weight: bold">
                            <td>{{gameData[(key) / 2].home_score}}</td>
                            <td>-</td>
                            <td>{{gameData[(key) / 2].away_score}}</td>
                        </tr>
                        <tr style="font-size:1.5em">
                            <td colspan="3">{{getQuarterTime(gameData[(key) / 2].time)}}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div style="float:left;display: inline-block; width:50%; margin-top:20px; min-height:220px">
                    <highchart
                        id="gauge{{key}}"
                        config="gaugeConfigs[(key) / 2]">
                    </highchart>
                </div>
            </div>
        </div>-->
    </div>
    <div style="clear: both;"></div>

</div>