<div ng-app="home-page" ng-controller="HomePageCtrl"
    <?php echo $this->ngInit(array('currentWeek')); ?>>
    <div style="width:100%;height:50px">
        <div style="float:left; display: inline-block; width:60%; padding-left:15px">
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active">
                    <a href="#offense" aria-controls="offense" role="tab" data-toggle="tab" ng-click="currentTab = 'offense'">
                        Team Offense
                    </a>
                </li>
                <li role="presentation">
                    <a href="#drives" aria-controls="drives" role="tab" data-toggle="tab" ng-click="currentTab = 'drives'">
                        Team Drives
                    </a>
                </li>
                <li style="margin-top:.5em;border:1px;float:right">
                    <span style="font-size:1.2em;font-weight:bold">Week Filter: </span>
                    <ui-select style="min-width:110px" ng-model="$parent.selectedWeek" theme="select2" ng-disabled="disabled" title="Select a Week">
                        <ui-select-match placeholder="Select a Week">
                            {{$select.selected.text}}
                        </ui-select-match>
                        <ui-select-choices repeat="week in weekOptions track by $index">
                            <div ng-bind-html="week.text | highlight: $select.search"></div>
                        </ui-select-choices>
                    </ui-select>
                </li>
            </ul>
        </div>
        <div ng-show="currentTab == 'offense'">
<!--            <div style="float:left; display: inline-block; width:19%; text-align:center; font-size:1.25em; text-decoration: underline">
                <span>Scoreboard</span>
            </div>-->
            <div style="float:left; display: inline-block; width:30%; text-align:center; font-size:1.25em; text-decoration: underline;">
            </div>
        </div>
        <div ng-show="currentTab == 'drives'" style="float:right;display:inline-block;margin-right:30px">
            <button class="btn filterButton" ng-click="driveFilter = 'all'" ng-class="{active: driveFilter == 'all'}">
                All
            </button>
            <button class="btn filterButton" ng-click="driveFilter = 'Q1'" ng-class="{active: driveFilter == 'Q1'}">
                1st Quarter
            </button>
            <button class="btn filterButton" ng-click="driveFilter = 'Q2'" ng-class="{active: driveFilter == 'Q2'}">
                2nd Quarter
            </button>
            <button class="btn filterButton" ng-click="driveFilter = 'Q3'" ng-class="{active: driveFilter == 'Q3'}">
                3rd Quarter
            </button>
            <button class="btn filterButton" ng-click="driveFilter = 'Q4'" ng-class="{active: driveFilter == 'Q4'}">
                4th Quarter
            </button>
        </div>
    </div>
    <div style="width:100%">

        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="offense">
                <div ng-repeat="(key, team) in teams" ng-if="currentTab == 'offense' && !loadingOffenseData">
                    <highchart
                        style="float:left;display: inline-block; width:30%; height:260px"
                        id="chart{{key}}"
                        config="chartConfigs[key]">
                    </highchart>
                    <div ng-if="(key % 2) && gaugeConfigs[(key - 1) / 2] !== null" style="float:left;display: inline-block; width:39%">
                        <div style="width:50%; float:left;display: inline-block;">
                            <table class="scoreboard">
                                <tbody>
                                <tr>
                                    <td>{{gameDataCheck[(key - 1) / 2].home_team}}</td>
                                    <td></td>
                                    <td>{{gameDataCheck[(key - 1) / 2].away_team}}</td>
                                </tr>
                                <tr style="font-size:2.5em; font-weight: bold">
                                    <td>{{gameDataCheck[(key - 1) / 2].home_score}}</td>
                                    <td>-</td>
                                    <td>{{gameDataCheck[(key - 1) / 2].away_score}}</td>
                                </tr>
                                <tr style="font-size:1.5em">
                                    <td colspan="3">
                                        <span ng-show="!gameDataCheck[(key - 1) / 2].finished">
                                            {{getQuarterTime(gameDataCheck[(key - 1) / 2].time)}}
                                        </span>
                                        <span ng-show="gameDataCheck[(key - 1) / 2].finished">
                                            Final
                                        </span>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                        <div style="width:50%; float:left; display:inline-block; min-height:240px">
                            <highchart
                                style="margin-top:20px;"
                                id="gauge{{key}}"
                                config="gaugeConfigs[(key - 1) / 2]">
                            </highchart>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div ng-if="(key % 2) && gaugeConfigs[(key - 1) / 2] === null" style="float:left;display: inline-block; width:39%;min-height:260px">
                        <div style="width:100%;text-align:center">
                            <div style="float:left; display:inline-block;width:50%">
                                <table class="scoreboard">
                                    <tbody>
                                    <tr>
                                        <td>{{gameDataCheck[(key - 1) / 2].home_team}}</td>
                                        <td></td>
                                        <td>{{gameDataCheck[(key - 1) / 2].away_team}}</td>
                                    </tr>
                                    <tr style="font-size:2.5em; font-weight: bold">
                                        <td>{{gameDataCheck[(key - 1) / 2].home_score}}</td>
                                        <td>-</td>
                                        <td>{{gameDataCheck[(key - 1) / 2].away_score}}</td>
                                    </tr>
                                    <tr style="font-size:1.5em">
                                        <td colspan="3">
                                        <span ng-show="!gameDataCheck[(key - 1) / 2].finished">
                                            {{getQuarterTime(gameDataCheck[(key - 1) / 2].time)}}
                                        </span>
                                        <span ng-show="gameDataCheck[(key - 1) / 2].finished">
                                            Final
                                        </span>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                            <div id="winnerImg{{(key - 1) / 2}}"
                                 style="float:left; display:inline-block;width:50%; vertical-align: middle; margin-top:15px;">
                            </div>
                        </div>
                        <br/>
                        <div style="width:100%;float:left;margin-top:15px;text-align:center">
                            <div>
                                <table class="table passerStats">
                                    <thead>
                                        <tr style="border:1px solid black;">
                                            <th>Name</th>
                                            <th>CMP/ATT</th>
                                            <th>PCT</th>
                                            <th>YDS</th>
                                            <th>TD(s)</th>
                                            <th>INT(s)</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr ng-repeat="passer in passerData[(key - 1) / 2]">
                                            <td>{{passer.name}}</td>
                                            <td>{{passer.cmp}}/{{passer.att}}</td>
                                            <td>{{passer.pct}}%</td>
                                            <td>{{passer.yds}}</td>
                                            <td>{{passer.tds}}</td>
                                            <td>{{passer.ints}}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
                <div ng-if="currentTab == 'offense' && loadingOffenseData"
                     style="float:left;display: inline-block;width:100%;height:260px;padding:10px 25px 0 25px;text-align:center">
                    <i class="fa fa-spinner fa-spin fa-3x" style="color:#002C5F"></i>
                </div>
            </div>
            <div role="tabpanel" class="tab-pane" id="drives">
                <div>

                    <highchart ng-repeat="(key, fieldPossessionConfig) in fieldPossessionConfigs"
                               ng-if="currentTab == 'drives' && !loadingPlayData"
                        style="float:left;display: inline-block;width:100%;height:260px;padding:10px 25px 0 25px"
                        id="fieldPossessionConfig{{key}}"
                        config="fieldPossessionConfigs[key]">
                    </highchart>
                    <div ng-if="currentTab == 'drives' && loadingPlayData"
                         style="float:left;display: inline-block;width:100%;height:260px;padding:10px 25px 0 25px;text-align:center">
                        <i class="fa fa-spinner fa-spin fa-3x" style="color:#002C5F"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
</div>